import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Ecell-view-website",
=======
  title: "Create Next App",
>>>>>>> 90dbf92c9990d305b8c64e43369db04052232d73
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full bg-black text-white">
        <div className="space-background fixed inset-0 z-0 overflow-hidden pointer-events-none">
          <div className="starfield" />
          <div className="meteor meteor-1" />
          <div className="meteor meteor-2" />
          <div className="meteor meteor-3" />
          <div className="meteor meteor-4" />
          <div className="meteor meteor-5" />
        </div>

        <div className="relative z-10 min-h-screen flex flex-col">{children}</div>
      </body>
=======
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 90dbf92c9990d305b8c64e43369db04052232d73
    </html>
  );
}
